import os

import openai
from flask import Flask, redirect, render_template, request, url_for
import random
import string

import subprocess
import shutil

# made the session file
session_code=''.join(random.choices(string.ascii_lowercase, k=20))
session_storytxt=session_code+'story.txt'
shutil.copyfile('story.txt', session_storytxt)


app = Flask(__name__)
# openai.api_key = os.getenv("OPENAI_API_KEY")
openai.api_key ="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"
s="""
 {}
"""

@app.route("/", methods=("GET", "POST"))
def index():
    if request.method == "POST":
        animal = request.form["animal"]
        response = openai.Completion.create(
            model="text-davinci-003",
            prompt=generate_prompt(animal),
            temperature=0.6,
            max_tokens=100
        )

        story = open(session_storytxt,'a')
        story.write(animal+ '\n Narrator: ' +response.choices[0].text+"\n User: ")
        story.close()
        
        response_img_prompt = openai.Completion.create(
            model="text-davinci-003",
            prompt=synthesize_image_prompt(response.choices[0].text),
            temperature=0.6,
            max_tokens=100
        )

        imgresponse =  openai.Image.create(
              prompt=response_img_prompt.choices[0].text+", grainy disposable polaroid photograph.",
              n=1,
              size="512x512"
        )
        print("synthesized image prompt: "+response_img_prompt.choices[0].text)
        return redirect(url_for("index", result=response.choices[0].text , imgresult= imgresponse['data'][0]['url']))

    result = request.args.get("result")
    imgresult = request.args.get("imgresult")


    return render_template("index.html", result=result, imgresult=imgresult)


def generate_prompt(animal):
    story = open(session_storytxt,'r')
    s=story.read()
    s+=' {} \n Narrator:'
    story.close()
    return s.format(
        animal.capitalize()
    )


def synthesize_image_prompt(event_):
    story = open(session_storytxt,'r')
    s=story.read()
    character=s.split('Describe yourself.')[1].replace('User:','')
    character=character.split('Narrator:')[0]
    print("CHARACTER: "+character)
    return """Write a short image prompt for DALL-E that concisely reflects the style and content below. 
    The image generated by the prompt will serve as an illustration in a choose-your-own-adventure story. The setting is NYC in 2001.

    A character described as this:'"""+character+"""', is experiencing this event in a choose-your-own-adventure story: '{}'. 
    """.format(
        event_.capitalize()

    )

def generate_image_prompt(animal):
    return """{} in New York City""".format(
        animal.capitalize()
    )
